daily_news/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('show_news.urls')),
]

show_news/urls.py
from django.urls import path
from . import views

app_name = 'show_news'

urlpatterns = [
    path('', views.show_news, name='show_news'),
    path('source/<str:source>', views.view_source, name='view_source'),
    path('details/<int:pk>', views.news_details, name='news_details'),
    path('settings/', views.settings, name='settings'),
    path('search/', views.search, name='search'),
]

show_news/models.py
from django.db import models

# Create your models here.


class Articles(models.Model):
    page_name = models.CharField(max_length=250)
    url = models.CharField(max_length=250, unique=True)
    title = models.CharField(max_length=250, unique=True)
    image_content_url = models.CharField(max_length=250)
    author = models.CharField(max_length=250)
    published_time = models.CharField(max_length=250)

    def __str__(self):
        return self.url


class Source_Of_News(models.Model):
    page_name = models.CharField(max_length=100, unique=True)
    page_url = models.CharField(max_length=250)

    def __str__(self):
        return self.page_name


class Skip_List(models.Model):
    page_name = models.CharField(max_length=100)
    url = models.CharField(max_length=250)

    def __str__(self):
        return self.url

show_news/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Articles, Source_Of_News
from .helper import _get_content, _get_news
from .extractors import *
import time
# Create your views here.

ARTICLE_PER_PAGE = 6


def show_news(request):
    displayed_news = {}
    all_sources = Source_Of_News.objects.all()
    page = 1
    start_id, end_id = 0, ARTICLE_PER_PAGE
    if 'view-more' in request.GET:
        page = int(request.GET['page']) + 1
        start_id = page*ARTICLE_PER_PAGE
        end_id = start_id + ARTICLE_PER_PAGE

    for source in all_sources:
        articles_objects = Articles.objects.filter(page_name=source.page_name).order_by(
            'pk').reverse()[start_id:end_id]

        displayed_news[source.page_name] = articles_objects

    context = {'displayed_news': displayed_news, 'page': page}
    return render(request, 'show_news/daily_news.html', context)


def view_source(request, source):
    NEWS_PER_PAGE = ARTICLE_PER_PAGE*2
    all_sources = Source_Of_News.objects.all()
    page = 1
    start_id, end_id = 0, NEWS_PER_PAGE
    if 'view-more' in request.GET:
        page = int(request.GET['page']) + 1
        start_id = page*NEWS_PER_PAGE
        end_id = start_id + NEWS_PER_PAGE

    articles_objects = Articles.objects.filter(
        page_name=source).order_by('pk').reverse()[start_id:end_id]

    context = {'displayed_news': articles_objects,
               'page': page, 'page_name': source, 'all_sources': all_sources}
    return render(request, 'show_news/source.html', context)


def news_details(request, pk):
    all_sources = Source_Of_News.objects.all()
    item = Articles.objects.get(pk=pk)
    related_news = Articles.objects.filter(page_name=item.page_name).filter(
        pk__lt=pk).order_by('pk').reverse()[0:4]

    news_extractor = _get_content(item.url)
    try:
        item.title = news_extractor.title
        item.image_content_url = news_extractor.img_of_content_url
        item.author = news_extractor.authors
        item.published_time = news_extractor.published_time
        item.save()
    except:
        pass

    message = news_extractor.messages

    context = {'message': message,
               'object': item,
               'content': news_extractor.content,
               'related_news': related_news,
               'all_sources': all_sources}

    return render(request, 'show_news/news_details.html', context)


def search(request):
    search_query = request.GET.get('search_box')
    all_sources = Source_Of_News.objects.all()
    result = Articles.objects.filter(title__icontains=search_query)
    message = 'Result for \"' + search_query + '\"'

    if not result:
        message = 'No result for \"' + search_query
        result = None

    context = {'result': result,
               'message': message,
               'all_sources': all_sources}

    return render(request, 'show_news/search.html', context)


def settings(request):
    pages = Source_Of_News.objects.all()
    context = {'object': pages}

    if request.method == 'POST':
        if 'add' in request.POST:
            url = request.POST['url']
            if len(pages) > 3:
                message = "Cannot add more sources due to the limitation of the databse. I am sorry!"
                return render(request, 'show_news/settings.html', {
                    'object': pages, 'message': message})
            if "https://" not in url:
                message = 'The URL is not valid. Perhaps you mean ' + 'https://www.' + url
                return render(request, 'show_news/settings.html', {
                    'object': pages, 'message': message})
            else:
                number_of_articles = _get_news(page_url=url,
                                               page_name=url.split(
                                                   '.')[1].title(),
                                               get_image_content_status=False)
                if not number_of_articles:
                    message = 'Cannot get content from ' + url
                else:
                    try:
                        item = Source_Of_News.objects.create(
                            page_url=url,
                            page_name=url.split('.')[1].title()
                        )
                    except Exception as e:
                        message = url + ' has already been in the database'
                        return render(request, 'show_news/settings.html', {
                            'object': pages, 'message': message})

                    message = 'Your newsfeed is updated with ' + \
                        str(number_of_articles) + ' new articles from ' + url
            pages = Source_Of_News.objects.all()
            return render(request, 'show_news/settings.html', {
                'object': pages, 'message': message})
        if 'remove_page' in request.POST:
            page_to_remove = request.POST.getlist('item')
            print(page_to_remove, request.POST)
            for page in page_to_remove:
                data = Source_Of_News.objects.filter(page_name=page)
                data.delete()
                data = Articles.objects.filter(page_name=page)
                data.delete()
            return redirect(request.path_info)
    return render(request, 'show_news/settings.html', context)

show_news/templates/show_news/daily_news.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'show_news/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'show_news/utilities.css' %}">
    <script src="https://kit.fontawesome.com/da72a545a2.js" crossorigin="anonymous"></script>

    <title>Daily News</title>
</head>

<body>
    <header id="header">
        <nav id="navbar" class="navbar">
            <div class="nav-container">

                <h1>
                    <a class="logo" href="{% url 'show_news:show_news' %}">
                        <i class="far fa-newspaper"></i> Daily News</a>
                </h1>
                <ul>
                    <li><a class="current" href="{% url 'show_news:show_news' %}">Home</a></li>
                    <li class="btn-source">
                        <a href="#">Sources</a>
                        <ul class="list-sources ">
                            {% for page_name, _ in displayed_news.items %}
                            <div class="source-name">
                                <li><a href="{% url 'show_news:view_source' page_name %}">{{page_name}}</a></li>
                            </div>
                            {% endfor %}
                            <div class="source-name">
                                <li><a href="{% url 'show_news:settings' %}">Setting</a></li>

                            </div>
                        </ul>
                    </li>
                    <li><a href="#about"> About</a></li>
                    <li><a class="btn-search" href="#"><i class="fas fa-search"></i></a></li>
                </ul>

            </div>
            <div id="search" class="search hidden">
                <form class="submit-field search-field" action="{% url 'show_news:search' %}">
                    <input type="text" name='search_box' placeholder="Search for...">
                    <button class="btn btn-light" type="submit">Search</button>
                </form>
            </div>
        </nav>
    </header>

    <main class="content wide-view">
        <section id="news-feed" class="news-feed">
            <div class="grid-items">
                {% for page_name, articles  in displayed_news.items %}
                {% for article in articles %}
                <div class="news-items">
                    {% if not article.image_content_url %}
                    <a href="{% url 'show_news:news_details' article.pk %}">
                        <img src="{% static 'show_news/img/default-img.jpg' %}">
                    </a>
                    {% else %}
                    <a href="{% url 'show_news:news_details' article.pk %}">
                        <img src="{{article.image_content_url}}">
                    </a>

                    {% endif %}

                    <p><a href="{% url 'show_news:news_details' article.pk %}"> {{ article.title }} </a></p>
                    <p> by <a href="{% url 'show_news:view_source' page_name %}"><span
                                class="text-primary">{{page_name}}</span></a></p>
                </div>
                {% endfor %}
                {% endfor %}
            </div>
            <div class="view-more">
                <form action=" {% url 'show_news:show_news' %}">
                    <input type="hidden" name="page" value="{{ page }}">
                    <input class="btn btn-light" type="submit" value="Show More News" name="view-more">
                </form>
            </div>
        </section>


    </main>
    <script>
        const search = document.querySelector('#header #search');
        btn_search = document.querySelector('.btn-search');
        btn_search.addEventListener('click', () => {
            search.classList.remove('hidden');
        })

        view_source = document.querySelector('.nav-container .list-sources');
        btn_source = document.querySelector('.navbar .btn-source');
        let btn_source_state = false;

        var view_news_from_source = function (event) {
            if (!btn_source_state) {
                view_source.style.display = 'flex';
                btn_source_state = true;
            }
            else {
                view_source.style.display = 'none';

                btn_source_state = false;
            }
        }
        btn_source.addEventListener('click', view_news_from_source, false);

    </script>
</body>

</html>

show_news/templates/show_news/get_content.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'show_news/style.css' %}">
</head>
<body>
    <header class="header-top"> 
        <div>
            <nav class="header-content">
                <a href="{% url 'show_news:show_news' %}">Today's news</a>
                <a style="margin-left: 35px" href="{% url 'show_news:get_content' %}">Get Content</a>
            </nav>
        </div>
    </header>
    
    <form class="get-content-form"  action="{% url 'show_news:get_content' %}" method="post">
    {% csrf_token %}
        <label>Paste your URL here</label><br>
        <input class="input-box" type="text" name="url" placeholder="URL of an article"> 
        <input class="button-submit" type="submit" value="Extract"> 
    </form>
    {% if error_message %}<p class="message"><strong>{{ error_message }}</strong></p>{% endif %}

    {% if news_object %}
        <table class="table-get-content">
            <tbody> 
                <tr>
                    <td>URL</td>
                    <td><a href="{{news_object.url}}"> {{news_object.url}}</a></td>
                </tr>
        {% if news_object.content %}
                <tr>
                    <td>Title</td> 
                    <td><b>{{news_object.title}}</b></td>
                </tr>
                <tr>
                    <td>Content image</td>
                    <td>
                         <div class="image-content-top">
                            <a href="{{news_object.url}}">
                                <img src="{{news_object.img_of_content_url}}" >
                            </a>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>Author</td>
                    <td>{{news_object.authors}}</td>
                </tr>
                <tr>
                    <td>Published time</td>
                    <td>{{news_object.published_time}}</td>
                </tr>
                <tr>
                    <td>Content</td>
                    <td style="white-space: pre-line">{{news_object.content}}</td>
                </tr>
        {% else %}
            </tbody>
        </table>
            <p class="message"> Cannot get content from that page</p>
        {% endif %}
    {% endif %}

</body>
</html>

show_news/templates/show_news/news_details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'show_news/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'show_news/utilities.css' %}">
    <script src="https://kit.fontawesome.com/da72a545a2.js" crossorigin="anonymous"></script>

    <title>Daily News</title>
</head>

<body>
    <header id="header">
        <nav id="navbar" class="navbar">
            <div class="nav-container">
                <h1>
                    <a class="logo" href="{% url 'show_news:show_news' %}">
                        <i class="far fa-newspaper"></i> Daily News</a>
                </h1>
                <ul>
                    <li><a class="current" href="{% url 'show_news:show_news' %}">Home</a></li>

                    <li class="btn-source">
                        <a href="#">Sources</a>
                        <ul class="list-sources ">
                            {% for page in all_sources %}
                            <div class="source-name">
                                <li><a href="{% url 'show_news:view_source' page.page_name %}">{{page.page_name}}</a>
                                </li>
                            </div>
                            {% endfor %}
                            <div class="source-name">
                                <li><a href="{% url 'show_news:settings' %}">Setting</a></li>

                            </div>
                        </ul>
                    </li>

                    <li><a href="#about"> About</a></li>
                    <li><a class="btn-search" href="#"><i class="fas fa-search"></i></a></li>
                </ul>
            </div>
            <div id="search" class="hidden">
                <form class="submit-field search-field" action="{% url 'show_news:search' %}">
                    <input type="text" name='search_box' placeholder="Search for...">
                    <button class="btn btn-light" type="submit">Search</button>
                </form>
            </div>
        </nav>
    </header>

    <main class="content normal-view">
        <section class="news-detail-header">
            <h2><a href="{{object.url}}">{{object.title}}</a></h2>
            {% if not object.image_content_url %}
            <a href="{{object.url}}"><img src="{% static 'show_news/img/default-img.jpg' %}"></a>
            {% else%}
            <a href="{{object.url}}"><img src="{{object.image_content_url}}"></a>
            {% endif %}
            <p> From <span class="text-primary">{{object.page_name}}</span> by <span
                    class="text-primary">{{object.author}}</span> | {{object.published_time}} </p>
            {% if message %} <p class="text-message">{{message}}</p>{% endif %}
        </section>
        <section class="news-detail-content">
            <div class="column-1">
                {{content|safe }}
            </div>
            <div class="column-2">
                <div class="item">
                    <p class="text-primary">More with {{object.page_name}}</p>
                </div>
                {% for article in related_news %}
                <div class="item">

                    <a href="{% url 'show_news:news_details' article.pk %}">
                        <img src="{{article.image_content_url}}">
                    </a>

                    <p class="related-news-title"><a href="{% url 'show_news:news_details' article.pk %}">
                            {{ article.title }} </a></p>
                </div>
                {% endfor %}
            </div>
        </section>

    </main>

    <script>
        const search = document.querySelector('.navbar #search')
        btn_search = document.querySelector('.btn-search')
        btn_search.addEventListener('click', () => {
            search.classList.remove('hidden');
        })

        view_source = document.querySelector('.nav-container .list-sources');
        btn_source = document.querySelector('.navbar .btn-source')
        let btn_source_state = false;

        var view_news_from_source = function (event) {
            if (!btn_source_state) {
                view_source.style.display = 'flex';
                btn_source_state = true;
            }
            else {
                view_source.style.display = 'none';

                btn_source_state = false;
            }
        }
        btn_source.addEventListener('click', view_news_from_source, false)
    </script>
</body>

</html>

show_news/templates/show_news/search.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'show_news/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'show_news/utilities.css' %}">
    <script src="https://kit.fontawesome.com/da72a545a2.js" crossorigin="anonymous"></script>

    <title>Daily News</title>
</head>

<body>
    <header id="header">
        <nav id="navbar" class="navbar">
            <div class="nav-container">
                <h1>
                    <a class="logo" href="{% url 'show_news:show_news' %}">
                        <i class="far fa-newspaper"></i> Daily News</a>
                </h1>
                <ul>
                    <li><a href="{% url 'show_news:show_news' %}">Home</a></li>
                    <li class="btn-source">
                        <a href="#">Sources</a>
                        <ul class="list-sources ">
                            {% for page in all_sources %}
                            <div class="source-name">
                                <li><a href="{% url 'show_news:view_source' page.page_name %}">{{page.page_name}}</a>
                                </li>
                            </div>
                            {% endfor %}
                            <div class="source-name">
                                <li><a href="{% url 'show_news:settings' %}">Setting</a></li>

                            </div>
                        </ul>
                    </li>
                    <li><a href="#about"> About</a></li>
                    <li><a class="current btn-search" href="#"><i class="fas fa-search"></i></a></li>
                </ul>
            </div>
            <div id="search">
                <form class="submit-field search-field" action="{% url 'show_news:search' %}">
                    <input type="text" name='search_box' placeholder="Search for...">
                    <button class="btn btn-light" type="submit">Search</button>
                </form>
            </div>
        </nav>
    </header>

    <main class="content normal-view">
        <div class="result-header">
            <p class="text-message">{{message}}</p>
        </div>

        <div class="grid-items">
            {% for article in result %}
            <div class="news-items">
                {% if not article.image_content_url %}
                <a href="{% url 'show_news:news_details' article.pk %}">
                    <img src="{% static 'show_news/img/default-img.jpg' %}">
                </a>
                {% else %}
                <a href="{% url 'show_news:news_details' article.pk %}">
                    <img src="{{article.image_content_url}}">
                </a>

                {% endif %}
                <p> <a href="{% url 'show_news:news_details' article.pk %}"> {{ article.title }} </a></p>
                <p> by <span class="text-primary">{{article.page_name}}</span></p>
            </div>
            {% endfor %}
        </div>
    </main>
    <script>
        view_source = document.querySelector('.nav-container .list-sources');
        btn_source = document.querySelector('.navbar .btn-source')
        let btn_source_state = false;

        var view_news_from_source = function (event) {
            if (!btn_source_state) {
                view_source.style.display = 'flex';
                btn_source_state = true;
            }
            else {
                view_source.style.display = 'none';

                btn_source_state = false;
            }
        }
        btn_source.addEventListener('click', view_news_from_source, false)
    </script>
</body>

</html>

show_news/templates/show_news/settings.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'show_news/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'show_news/utilities.css' %}">
    <script src="https://kit.fontawesome.com/da72a545a2.js" crossorigin="anonymous"></script>

    <title>Daily News</title>
</head>

<body>
    <header id="header">
        <nav id="navbar" class="navbar">
            <div class="nav-container">
                <h1>
                    <a class="logo" href="{% url 'show_news:show_news' %}">
                        <i class="far fa-newspaper"></i> Daily News</a>
                </h1>
                <ul>
                    <li><a href="{% url 'show_news:show_news' %}">Home</a></li>
                    <li class="btn-source">
                        <a class="current" href="#">Sources</a>
                        <ul class="list-sources ">
                            {% for item in object %}
                            <div class="source-name">
                                <li><a href="{% url 'show_news:view_source' item.page_name %}">{{item.page_name}}</a>
                                </li>
                            </div>
                            {% endfor %}
                            <div class="source-name">
                                <li><a href="{% url 'show_news:settings' %}">Setting</a></li>

                            </div>
                        </ul>
                    </li>
                    <li><a href="#about"> About</a></li>
                    <li><a class="btn-search" href="#"><i class="fas fa-search"></i></a></li>
                </ul>
            </div>
            <div id="search" class="hidden">
                <form class="submit-field search-field" action="{% url 'show_news:search' %}">
                    <input type="text" name='search_box' placeholder="Search for...">
                    <button class="btn btn-light" type="submit">Search</button>
                </form>
            </div>
        </nav>
    </header>

    <main class="content normal-view setting">
        <section id="sources">
            <div class="setting-name">
                <h2> Manage Sources</h2>
                <form class="submit-field" method='post' action="{% url 'show_news:settings' %}">{% csrf_token %}
                    <label class="label-input-text" for="url">Title</label>
                    <input type="text" name="url" id="url">
                    <input class="btn btn-light" type="submit" name="add" value=" Add ">
                </form>
                {% if message %}
                <p class="text-message"> {{message}}</p>
                {% endif %}
            </div>

            <div class="setting-properties">
                {% if object %}
                <form class="setting-page-items" method='post' action="{% url 'show_news:settings' %}">{% csrf_token %}
                    {% for item in object %}
                    <div class="setting-page-item">
                        <input type="checkbox" name="item" id='{{item.page_name}}' value="{{item.page_name}}">
                        <label for="{{item.page_name}}"> {{item.page_name}}</label>
                    </div>
                    {% endfor %}
                    <div class="setting-page-item btn-remove">
                        <input class="btn btn-dark" type="submit" name="remove_page" value="Remove">
                    </div>
                </form>

                {% else %}
                <p class="text-message">There is nothing in the database, please add some pages</p>
                {% endif %}

            </div>
        </section>

    </main>

    <script>
        const search = document.querySelector('.navbar #search')
        btn_search = document.querySelector('.btn-search')
        btn_search.addEventListener('click', () => {
            search.classList.remove('hidden');
        })

        view_source = document.querySelector('.nav-container .list-sources');
        btn_source = document.querySelector('.navbar .btn-source')
        let btn_source_state = false;

        var view_news_from_source = function (event) {
            if (!btn_source_state) {
                view_source.style.display = 'flex';
                btn_source_state = true;
            }
            else {
                view_source.style.display = 'none';

                btn_source_state = false;
            }
        }
        btn_source.addEventListener('click', view_news_from_source, false)

    </script>
</body>

</html>

show_news/templates/show_news/source.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'show_news/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'show_news/utilities.css' %}">
    <script src="https://kit.fontawesome.com/da72a545a2.js" crossorigin="anonymous"></script>

    <title>Daily News</title>
</head>

<body>
    <header id="header">
        <nav id="navbar" class="navbar">
            <div class="nav-container">
                <h1>
                    <a class="logo" href="{% url 'show_news:show_news' %}">
                        <i class="far fa-newspaper"></i> Daily News</a>
                </h1>
                <ul>
                    <li><a href="{% url 'show_news:show_news' %}">Home</a></li>
                    <li class="btn-source">
                        <a class="current" href="#">Sources</a>
                        <ul class="list-sources ">
                            {% for page in all_sources %}
                            <div class="source-name">
                                <li><a href="{% url 'show_news:view_source' page.page_name %}">{{page.page_name}}</a>
                                </li>
                            </div>
                            {% endfor %}
                            <div class="source-name">
                                <li><a href="{% url 'show_news:settings' %}">Setting</a></li>

                            </div>
                        </ul>
                    </li>
                    <li><a href="#about"> About</a></li>
                    <li><a class="btn-search" href="#"><i class="fas fa-search"></i></a></li>
                </ul>
            </div>
            <div id="search" class="hidden">
                <form class="submit-field search-field" action="{% url 'show_news:search' %}">
                    <input type="text" name='search_box' placeholder="Search for...">
                    <button class="btn btn-light" type="submit">Search</button>
                </form>
            </div>
        </nav>
    </header>

    <main class="content wide-view">
        <section id="news-feed" class="news-feed">
            <div class="grid-items">
                {% for article in displayed_news %}
                <div class="news-items">
                    {% if not article.image_content_url %}
                    <a href="{% url 'show_news:news_details' article.pk %}">
                        <img src="{% static 'show_news/img/default-img.jpg' %}">
                    </a>
                    {% else %}
                    <a href="{% url 'show_news:news_details' article.pk %}">
                        <img src="{{article.image_content_url}}">
                    </a>

                    {% endif %}

                    <p><a href="{% url 'show_news:news_details' article.pk %}"> {{ article.title }} </a></p>
                    <p> by <span class="text-primary">{{page_name}}</span></p>
                </div>
                {% endfor %}
            </div>
            <div class="view-more">

                <form action=" {% url 'show_news:view_source' page_name %}">
                    <input type="hidden" name="page" value="{{ page }}">
                    <input class="btn btn-light" type="submit" value="Show More News" name="view-more">
                </form>
            </div>
        </section>


    </main>
    <script>
        const search = document.querySelector('.navbar #search')
        btn_search = document.querySelector('.btn-search')
        btn_search.addEventListener('click', () => {
            search.classList.remove('hidden');
        })

        view_source = document.querySelector('.nav-container .list-sources');
        btn_source = document.querySelector('.navbar .btn-source')
        let btn_source_state = false;

        var view_news_from_source = function (event) {
            if (!btn_source_state) {
                view_source.style.display = 'flex';
                btn_source_state = true;
            }
            else {
                view_source.style.display = 'none';

                btn_source_state = false;
            }
        }
        btn_source.addEventListener('click', view_news_from_source, false)
    </script>
</body>

</html>